standalone_tags:
  [
    { id: 1, size: 0.024 },
    { id: 2, size: 0.024 },
    { id: 2, size: 0.024 },
    { id: 3, size: 0.024 },
    { id: 4, size: 0.024 },
    { id: 5, size: 0.024 },
    { id: 6, size: 0.024 }
  ]

tag_bundles:
  [
    {
      name: 'my_bundle',
      layout:
        [
          { id: 10, size: 0.05, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0 }
        ]
    }
  ]
